openapi: 3.0.0
paths:
  '/patients/{id}':
    get:
      operationId: getById
      parameters:
        -
          name: id
          in: path
          description: 'ID of patient to return'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: 'Patient was not found'
        '200':
          description: 'Patient was found'
    delete:
      summary: 'Deletes a patient'
      description: ''
      operationId: deletePatients
      parameters:
        -
          name: id
          in: path
          description: 'Patient id to delete'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: 'patient not found'
        '200':
          description: 'patient successful deletion'
  /patients:
    post:
      operationId: createPatient
      requestBody:
        $ref: '#/components/requestBodies/patients'
      responses:
        '418':
          description: 'Patient was not created'
        '201':
          description: 'Patient was created'
components:
  schemas:
    PatientDTO:
      title: 'Le PatientDTO'
      description: 'Le PatientDTO'
      required:
        - nom
        - prenom
        - rdvsDTO
        - ville
        - rue
        - date_naissance
        - mail
        - mdp
        - tel
      properties:
        id:
          type: integer
          format: int64
        nom:
          title: nom
          description: 'PatientDTO nom'
          type: string
        prenom:
          title: prenom
          description: 'PatientDTO prenom'
          type: string
        rdvsDTO:
          title: rdvsDTO
          description: 'PatientDTO rdvsDTO'
        ville:
          title: ville
          description: 'PatientDTO ville'
          type: string
        rue:
          title: rue
          description: 'PatientDTO rue'
          type: string
        date_naissance:
          title: dateNaissance
          description: 'PatientDTO dateNaissance'
        mail:
          title: mail
          description: 'PatientDTO mail'
          type: string
        mdp:
          title: mdp
          description: 'PatientDTO mdp'
          type: string
        tel:
          title: tel
          description: 'PatientDTO tel'
          type: integer
      type: object
    PraticienDTO:
      title: 'Le PraticientDTO'
      description: 'Le PraticientDTO'
      required:
        - nom
        - prenom
        - etablissements
        - specialites
        - mail
        - mdp
        - tel
      properties:
        id:
          type: integer
          format: int64
        nom:
          title: nom
          description: 'PraticienDTO nom'
          type: string
        prenom:
          title: prenom
          description: 'PraticienDTO prenom'
          type: string
        etablissements:
          title: etablissements
          description: 'PraticienDTO etablissements'
        specialites:
          title: spcecialites
          description: 'PraticienDTO spcecialites'
        mail:
          title: mail
          description: 'PraticienDTO mail'
          type: string
        mdp:
          title: mdp
          description: 'PraticienDTO mdp'
          type: string
        tel:
          title: tel
          description: 'PraticienDTO tel'
          type: integer
      type: object
    SpecialiteDTO:
      title: 'La SpecialitetDTO'
      description: 'La SpecialitetDTO'
      required:
        - designation
      properties:
        designation:
          title: designation
          description: 'SpecialitetDTO designation'
      type: object
    Patient:
      title: 'Le Patient'
      description: 'Le Patient'
      required:
        - ''
      properties:
        id:
          title: id
          description: 'Patient id'
          type: integer
      type: object
