openapi: 3.0.0
paths:
  '/patients/{id}':
    get:
      operationId: getById
      parameters:
        -
          name: id
          in: path
          description: 'ID of patient to return'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: 'Patient was not found'
        '200':
          description: 'Patient was found'
    delete:
      summary: 'Deletes a patient'
      description: ''
      operationId: deletePatients
      parameters:
        -
          name: id
          in: path
          description: 'Patient id to delete'
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '404':
          description: 'patient not found'
        '200':
          description: 'patient successful deletion'
  /patients:
    post:
      operationId: createPatient
      requestBody:
        $ref: '#/components/requestBodies/patients'
      responses:
        '418':
          description: 'Patient was not created'
        '201':
          description: 'Patient was created'
components:
  schemas:
    PatientDTO:
      title: 'Le PatientDTO'
      description: 'Le PatientDTO'
      required:
        - nom
      properties:
        nom:
          title: nom
          description: 'PatientDTO nom'
      type: object
    Patient:
      title: 'Le Patient'
      description: 'Le Patient'
      required:
        - ''
      properties:
        id:
          title: id
          description: 'Patient id'
          type: integer
      type: object
